### ISSUE TITLE
请问call_user_func_array和您的call函数有什么区别？

### ISSUE THREAD

**Issue by erikaemma** [php-mylib/php-utils#1]
https://github.com/php-toolkit/php-utils/blob/master/src/PhpHelper.php中的call函数，使用判断类型再分类型调用的。请问直接改成如下格式有何区别？
```php
public function call(callable $method, ...$args) {
 return call_user_func_array($method, $args);
}
```

**Comment by inhere** [comment]
😄 使用没多大区别。

call分析后直接调用目标方法。不需要像call_user_func_array通过反射调用，有损耗
